enum ActionTypes {
  BIOMETRIC_AUTHENTICATE = '@@mytodo/authentication/BIOMETRIC_AUTHENTICATE',
  BIOMETRIC_AUTHENTICATE_SUCCESS = '@@mytodo/authentication/BIOMETRIC_AUTHENTICATE_SUCCESS',
  BIOMETRIC_AUTHENTICATE_FAIL = '@@mytodo/authentication/BIOMETRIC_AUTHENTICATE_FAIL',

  RESET_AUTHENTICATION = '@@mytodo/authentication/RESET_AUTHENTICATION',

  CHECK_HAS_BIOMETRIC_HARDWARE = '@@mytodo/authentication/CHECK_HAS_BIOMETRIC_HARDWARE',
  CHECK_HAS_BIOMETRIC_HARDWARE_SUCCESS = '@@mytodo/authentication/CHECK_HAS_BIOMETRIC_HARDWARE_SUCCESS',
  CHECK_HAS_BIOMETRIC_HARDWARE_FAIL = '@@mytodo/authentication/CHECK_HAS_BIOMETRIC_HARDWARE_FAIL',

  CHECK_BIOMETRICS_ENROLLED = '@@mytodo/authentication/CHECK_BIOMETRICS_ENROLLED',
  CHECK_BIOMETRICS_ENROLLED_SUCCESS = '@@mytodo/authentication/CHECK_BIOMETRICS_ENROLLED_SUCCESS',
  CHECK_BIOMETRICS_ENROLLED_FAIL = '@@mytodo/authentication/CHECK_BIOMETRICS_ENROLLED_FAIL',
}

export default ActionTypes;
